### ISSUE TITLE
lkvm dumps core

### ISSUE THREAD

**Issue by keerthanabs1** [clearlinux/kvmtool#4]
I am trying to run virtual machine using the tools .... and I see a core dump ... the dump points to location where it complains for missing kernel parameter. Can you please check and let me know what could be missing here?

./lkvm run -d ./linux-0.2.img -k ../../linux-3.13.0/arch/x86/boot/bzImage --network virtio

**Comment by jamesodhunt** [comment]
Please can you provide the core dump details you are referring to?

Note that this version of kvmtool is designed to be called with --oci-config and --oci-runtime, but the default command-line options should of course still work for testing.

**Comment by keerthanabs1** [comment]
Here s the core dump details 

(gdb) where
#0  __strstr_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strstr-sse2-unaligned.S:40
#1  0x0000000000405a72 in kvm_cmd_run_init (argc=<optimized out>, argv=<optimized out>) at builtin-run.c:608
#2  0x000000000040673d in kvm_cmd_run (argc=<optimized out>, argv=<optimized out>, prefix=<optimized out>) at builtin-run.c:659
#3  0x00000000004131f2 in handle_command (command=0x62c700 <kvm_commands>, argc=3, argv=0x7fffe0559f40) at kvm-cmd.c:84
#4  0x00007f6334c3fec5 in __libc_start_main (main=0x403840 <main>, argc=4, argv=0x7fffe0559f38, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffe0559f28) at libc-start.c:287
#5  0x0000000000403c62 in _start ()

(gdb) frame 1
#1  0x0000000000405a72 in kvm_cmd_run_init (argc=<optimized out>, argv=<optimized out>) at builtin-run.c:608
608     } else if (!strstr(kvm->cfg.kernel_cmdline, "root=")) {

(gdb) p kvm->cfg.kernel_cmdline
$1 = 0x0

I have provided the "--kernel" or "-k" option when I execute the tool.

**Comment by xnox** [comment]
http://article.gmane.org/gmane.comp.emulators.kvm.devel/142415 ?

**Comment by keerthanabs1** [comment]
Thanks, this worked.

**Comment by xnox** [comment]
@jamesodhunt have you, or could you please cherry-pick the patch mentioned above?
